# Generated by Django 5.1.5 on 2025-01-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='field_type',
            field=models.CharField(choices=[('IntegerField', 'Integer'), ('FloatField', 'Float'), ('DecimalField', 'Decimal'), ('DateField', 'Date'), ('DateTimeField', 'DateTime'), ('BooleanField', 'Boolean'), ('CharField', 'Text'), ('TextField', 'Long Text'), ('EmailField', 'Email'), ('URLField', 'URL'), ('FileField', 'File'), ('ImageField', 'Image')], default='CharField', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='aggregation',
            field=models.CharField(blank=True, choices=[('COUNT', 'Count'), ('SUM', 'Sum'), ('AVG', 'Average'), ('MIN', 'Minimum'), ('MAX', 'Maximum')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='field_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
