# Generated by Django 5.1.5 on 2025-01-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportcolumn_field_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcolumn',
            name='field_type',
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='aggregation',
            field=models.CharField(blank=True, choices=[('', 'No Aggregation'), ('COUNT', 'Count'), ('SUM', 'Sum'), ('AVG', 'Average'), ('MIN', 'Minimum'), ('MAX', 'Maximum')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='field_path',
            field=models.CharField(help_text='Dot notation path to the field', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
