# Generated by Django 5.1.5 on 2025-02-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_reportcolumn_field_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='asc', max_length=4)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorting', to='report.report')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('report', 'field_path')},
            },
        ),
    ]
