# Generated by Django 5.1.5 on 2025-02-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_reportcolumn_formula_reportcolumn_is_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='condition',
            field=models.TextField(blank=True, help_text="Condition for conditional aggregations (e.g., 'value > 100')", null=True),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('QUARTER', 'Quarterly'), ('YEAR', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='weight_field',
            field=models.CharField(blank=True, help_text='Field to use for weighted calculations', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='window_size',
            field=models.IntegerField(blank=True, help_text='Size of window for moving averages', null=True),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='aggregation',
            field=models.CharField(blank=True, choices=[('', 'No Aggregation'), ('COUNT', 'Count'), ('SUM', 'Sum'), ('AVG', 'Average'), ('MIN', 'Minimum'), ('MAX', 'Maximum'), ('COUNT_DISTINCT', 'Count Distinct'), ('COUNT_IF', 'Count If'), ('SUM_IF', 'Sum If'), ('STDDEV', 'Standard Deviation'), ('VARIANCE', 'Variance'), ('MEDIAN', 'Median'), ('MONTH_SUM', 'Monthly Sum'), ('YEAR_SUM', 'Yearly Sum'), ('YOY_GROWTH', 'Year over Year Growth'), ('RUNNING_TOTAL', 'Running Total'), ('RANK', 'Rank'), ('MOVING_AVG', 'Moving Average'), ('PERCENTILE_25', '25th Percentile'), ('PERCENTILE_50', 'Median (50th Percentile)'), ('PERCENTILE_75', '75th Percentile'), ('PERCENTILE_90', '90th Percentile')], max_length=20),
        ),
    ]
