# Generated by Django 5.1.6 on 2025-02-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_reportcolumn_condition_reportcolumn_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='conditional_formatting',
            field=models.JSONField(blank=True, help_text='\n    JSON configuration for conditional formatting, e.g.:\n    {\n        "rules": [\n            {\n                "condition": "value > 1000",\n                "style": {"color": "red", "font-weight": "bold"}\n            }\n        ]\n    }\n    ', null=True),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Currency symbol for currency fields', max_length=5),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='date_format',
            field=models.CharField(default='YYYY-MM-DD', help_text='Date format string', max_length=50),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='decimal_places',
            field=models.IntegerField(default=2, help_text='Number of decimal places for numeric fields'),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='formatting_type',
            field=models.CharField(choices=[('number', 'Number'), ('currency', 'Currency'), ('percentage', 'Percentage'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('text', 'Text')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='is_sortable',
            field=models.BooleanField(default=True, help_text='Whether this column can be sorted'),
        ),
    ]
